# Generated by Django 3.2.7 on 2024-02-23 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('storage', models.PositiveBigIntegerField(default=5)),
                ('already_use', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_mail', models.EmailField(max_length=254)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('logout_count', models.PositiveIntegerField(default=0)),
                ('image_detect_count', models.PositiveIntegerField(default=0)),
                ('view_detect_count', models.PositiveIntegerField(default=0)),
                ('image_restructure_count', models.PositiveIntegerField(default=0)),
                ('llms_count', models.PositiveIntegerField(default=0)),
                ('images_infosys_count', models.PositiveIntegerField(default=0)),
                ('models_count', models.PositiveIntegerField(default=0)),
                ('research_count', models.PositiveIntegerField(default=0)),
                ('dataPreprocess_count', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
